#!/bin/sh

ADP=$(ls /sys/class/power_supply | head -1)
BAT=$(ls /sys/class/power_supply | tail -1)

capacity=$(cat /sys/class/power_supply/$BAT/capacity)
status=$(cat /sys/class/power_supply/$BAT/status)
aconline=$(cat /sys/class/power_supply/$ADP/online)


capicon() {
  if [ $1 -le 10 ]; then
    printf ""
  elif [ $1 -le 25 ]; then
    printf ""
  elif [ $1 -le 50 ]; then
    printf ""
  elif [ $1 -le 100 ]; then
    printf " "
  elif [ $1 -eq 100 ]; then
    printf ""
  fi
}

des() {
  capicon $1
  if [ $2 -eq 1 ]; then
    printf "$1 \n"
  else
    printf "$1\n"
  fi
}

des $capacity $aconline
des $capacity $aconline

if [[ $capacity -le 20 && $aconline -eq 0 ]]; then
  echo "#FF0000"
else
  echo "#3b9a9c"
fi
