#!/bin/bash

case $BLOCK_BUTTON in
  1) $TERMINAL -e nmtui ;;
esac

hash iw || (printf "install iw\\n" && exit)

INTERFACE="${BLOCK_INSTANCE:-$(iw dev | awk '/Interface/ {print $2}')}"

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
([[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
  [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]) &&
    echo "" && echo "" && echo "#FF0000" && exit

ssid=$(iw dev | awk '/ssid/ {print $2}')

icon=""
echo "$icon $ssid" # full text
echo "$icon $ssid" # short text

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

# color
if [[ $QUALITY -ge 80 ]]; then
    echo "#1ee3cf"
elif [[ $QUALITY -lt 80 ]]; then
    echo "#FFF600"
elif [[ $QUALITY -lt 60 ]]; then
    echo "#FFAE00"
elif [[ $QUALITY -lt 40 ]]; then
    echo "#FF0000"
fi
