#!/bin/sh

export PRIMARY_DISPLAY=`xrandr | awk '/ connected/{print $1}'`

xidlehook \
    `# Don't lock when there's a fullscreen application` \
    --not-when-fullscreen \
    `# Don't lock when there's audio playing` \
    --not-when-audio \
    `# Dim the screen after 60 seconds, undim if user becomes active` \
    --timer 300 \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness .7' \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness 1' \
    `# Undim & lock after 10 more seconds` \
    --timer 10 \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness 1; lock' \
    '' \
    `# Finally, suspend an hour after it locks` \
    --timer 300 \
    'systemctl suspend' \
    ''
