#!/bin/sh

hash pactl || (echo 'install pulseaudio-ctl' && exit)

getDefaultSink() {
  pacmd list-sinks | awk '/\* index/ {printf $3}'
}

case $1 in
  +) pactl set-sink-volume $(getDefaultSink) +10%;;
  -) pactl set-sink-volume $(getDefaultSink) -10%;;
  m) pactl set-sink-mute $(getDefaultSink) toggle;;
esac

pkill -RTMIN+10 i3blocks 2>/dev/null
